### ISSUE TITLE
what method you are using to create code and access token

### ISSUE THREAD

**Issue by shahryarjb** [malach-it/boruta_auth#15]
Hello, sorry to create this issue, I have read your project but I could not be able to find what method you are using to create `code` for redirect url and `access/refresh` token without `jwt`.
the other question is why you did not use Plug `encryption` for `code` not access token?
Thank you

**Comment by patatoid** [comment]
Hi,

There is no usage of JWT in the suggested implementation. You can implement a new `TokenGenerator`and inject it to craft your own access_tokens.

I don't know about `Plug`encryption, if you can see a usage of this in the repository, you can make a Pull Request.
