### ISSUE TITLE
Allow skipping interactive step during migration

### ISSUE THREAD

**Issue by chulkilee** [malach-it/boruta_auth#16]
https://github.com/malach-it/boruta_auth/blob/2.3.2/lib/mix/tasks/boruta.gen.migration.ex#L104

This makes docker compose run stuck on the first run (which generates migrations)

**Comment by patatoid** [comment]
Hi @chulkilee ,

You can run the container in interactive mode:

```
docker run -it <name of the image>
```

That said, I can remove the REPL since I have enough analytics for the package.

Thank you for your feedback, keep you posted about the update.

**Comment by patatoid** [comment]
I removed the REPL as in https://github.com/malach-it/boruta_auth/commit/b378bcdd0ceaf2a5f03f2d201266b7a8d0575524

I also published a new version of the package https://hex.pm/packages/boruta

Hope that helps.

**Comment by chulkilee** [comment]
Confirmed 2.3.3 removed it! :tada: https://diff.hex.pm/diff/boruta/2.3.2..2.3.3 Closing it as this is done

Could you update the changelog for 2.3.3?

**Comment by patatoid** [comment]
changelog is available here https://hexdocs.pm/boruta/changelog.html
