### ISSUE TITLE
Thoughts on Authorization Server Obtains End-User Consent/Authorization

### ISSUE THREAD

**Issue by chulkilee** [malach-it/boruta_auth#18]
From https://openid.net/specs/openid-connect-core-1_0.html#Consent

> 3.1.2.4 Authorization Server Obtains End-User Consent/Authorization
>
> Once the End-User is authenticated, the Authorization Server MUST obtain an authorization decision before releasing information to the Relying Party. When permitted by the request parameters used, this MAY be done through an interactive dialogue with the End-User that makes it clear what is being consented to or by establishing consent via conditions for processing the request or other means (for example, via previous administrative consent). Sections [2](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) and [5.3](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) describe information release mechanisms.

Since this is "MUST", I believe it would be great if boruta includes the consent phase as configuration option.

boruta-server has it as a part of boruta_identity ([link](https://github.com/malach-it/boruta-server/blob/371498a996888c34e9d58be39b9720304f5999fe/apps/boruta_identity/lib/boruta_identity/accounts/consents.ex)) - btw.

**Comment by patatoid** [comment]
The server is designed to keep user data out of the authorization domain brought by OAuth 2.0 / OIDC. I think the consent is to be implemented in the application layer along with the user business logic.

Does it make sense?

**Comment by chulkilee** [comment]
I agree that adding the whole consent feature to boruta core doesn't make sense - but we may add no-op callback or generate code for this.

**Comment by patatoid** [comment]
How would you see such an update? As it is implemented in boruta-server, there is no interaction with the core domain.
