### ISSUE TITLE
Support device code flow

### ISSUE THREAD

**Issue by Kloenk** [malach-it/boruta_auth#2]
Oauth2 contains an extension to use a device code for devices that do not have a (web)ui. This grant type (and everything else required) is not available.

I would love if the device code flow would be implemented, but It could be a good start, to allow grant extension and not restrict on the fixed grant set (https://www.rfc-editor.org/rfc/rfc6749#section-4.5).

https://www.rfc-editor.org/rfc/rfc8628#section-3.4

**Comment by patatoid** [comment]
Hi Finn,

Thank you for the interest you got in the library.

The implementation of the device code flow is not in my current roadmap. That said, the objective is to be the wider possible in the implementation of the specifications, thus I'll add those implementations to it knowing that there is already quite a lot of work to be done and the priority would be low. I am also open to contributions if you are pleased to make any.

With care

**Comment by Kloenk** [comment]
The main think that would be helpfull, is to not restrict the grant types, but I'm not sure how to best do that. One option would be just replace the current hard coded list with a build time config, would that make sense?

**Comment by patatoid** [comment]
In this implementation, the grant type is used to route the request to the according OAuth flow business rules. Thus opening the values would lead to a dead end.

Device code flow usage would imply also its implementation. I think this work has also to be done along with the addition of the grant type value consideration.
