### ISSUE TITLE
JWKs do not specify their use (sig/enc), but seems not required by spec

### ISSUE THREAD

**Issue by lnchan** [malach-it/boruta_auth#5]
It seems that some Clients require the `"use"` field on JWKs in order to find the matching signing keys from the JWKS, most likely as a way to prevent encryption keypairs from being used to verify signed tokens or vice-versa.

I am not sure if this is a requirement as per the OpenID Connect spec; if it is not, it would probably be preferable to correct the clients instead.

RFC 7517 (4.2) does specify it as "optional, unless the application requires its presence". OpenID Connect Core 1.0 makes no mention of the requirement of such a field (and considering the certifications, I would expect it is not required).

Feel free to ignore this issue, as it seems to be Client-specific behaviour that is most likely wrong.

**Comment by patatoid** [comment]
Hi @lnchan ,

Thank you for the interest you have in my work!

As it is an optional claim in the JWT specification, I think it can be a good development/value cost improvement.

If you are about coding the edits, adding a static "use" claim [here](https://github.com/malach-it/boruta_auth/blob/master/lib/boruta/oauth/schemas/id_token.ex#L80), go with it. Else, I can perform the changes.

**Comment by lnchan** [comment]
Sure, I can look into that! Are the keys used for encryption purposes though, or is each key exclusively used for signing? (considering they are RSA keys, I would expect only signing, but I'd prefer to make sure of that)

(au fait, même si j'ai globalement compris l'idée, je suis pas sûre de comprendre exactement "if you are about coding the edits" ; désolée!)

**Comment by patatoid** [comment]
With this server, the ID tokens are signed (content is accessible) and not encrypted (you need the key to see the content), then following the spec you highlight it would be the `sig` value.

Sorry for my English, you can open a Pull Request as you like.

Merci pour la touche française :)

**Comment by lnchan** [comment]
Don't be sorry for your English!
Thank you for your precisions, but mostly, thank you for this project. I've been looking for OpenID Connect implementations due to the lack of easy-to-host providers, and your library helps a lot; it is extremely high quality (and in Elixir, a language I appreciate a lot).

I'll be looking into that as soon as I can!

**Comment by patatoid** [comment]
If you are looking for a full provider there is also a product of mine built on top of this library https://github.com/malach-it/boruta-server. Have a look, all feedback is very welcome :)

**Comment by patatoid** [comment]
Hi @lnchan 

Any update on this?
